export default {
  background: ["background", "foreground", "default", "default-foreground"],
  border: ["border"],
  text: ["text"],
  colors: [
    "bg-primary",
    "bg-primary-foreground",
    "bg-primary-shade1",
    "bg-primary-shade2",
    "bg-primary-shade3",
    "bg-primary-shade4",
    "bg-primary-shade5",
    "bg-secondary",
    "bg-secondary-foreground",
    "bg-destructive",
    "bg-destructive-foreground",
    "bg-muted",
    "bg-muted-foreground",
    "bg-accent",
    "bg-accent-foreground",
    "bg-popover",
    "bg-popover-foreground",
    "bg-card",
    "bg-card-foreground",
  ],
  palletes: [
    "bg-black",
    "bg-white",
    // "bg-gray-dark-100",
    // "bg-gray-dark-200",
    // "bg-gray-dark-300",
    // "bg-gray-dark-400",
    // "bg-gray-dark-500",
    // "bg-gray-dark-600",
    // "bg-gray-dark-700",
    // "bg-gray-dark-800",
    // "bg-gray-dark-900",
    // "bg-gray-dark-1000",
    // "bg-gray-dark-1100",
    // "bg-gray-dark-1200",
    // "bg-gray-dark-alpha-100",
    // "bg-gray-dark-alpha-200",
    // "bg-gray-dark-alpha-300",
    // "bg-gray-dark-alpha-400",
    // "bg-gray-dark-alpha-500",
    // "bg-gray-dark-alpha-600",
    // "bg-gray-dark-alpha-700",
    // "bg-gray-dark-alpha-800",
    // "bg-gray-dark-alpha-900",
    // "bg-gray-dark-alpha-1000",
    // "bg-gray-dark-alpha-1100",
    // "bg-gray-dark-alpha-1200",
    // "bg-gray-light-100",
    // "bg-gray-light-200",
    // "bg-gray-light-300",
    // "bg-gray-light-400",
    // "bg-gray-light-500",
    // "bg-gray-light-600",
    // "bg-gray-light-700",
    // "bg-gray-light-800",
    // "bg-gray-light-900",
    // "bg-gray-light-1000",
    // "bg-gray-light-1100",
    // "bg-gray-light-1200",
    // "bg-gray-light-alpha-100",
    // "bg-gray-light-alpha-200",
    // "bg-gray-light-alpha-300",
    // "bg-gray-light-alpha-400",
    // "bg-gray-light-alpha-500",
    // "bg-gray-light-alpha-600",
    // "bg-gray-light-alpha-700",
    // "bg-gray-light-alpha-800",
    // "bg-gray-light-alpha-900",
    // "bg-gray-light-alpha-1000",
    // "bg-gray-light-alpha-1100",
    // "bg-gray-light-alpha-1200",
    // "bg-slate-dark-100",
    // "bg-slate-dark-200",
    // "bg-slate-dark-300",
    // "bg-slate-dark-400",
    // "bg-slate-dark-500",
    // "bg-slate-dark-600",
    // "bg-slate-dark-700",
    // "bg-slate-dark-800",
    // "bg-slate-dark-900",
    // "bg-slate-dark-1000",
    // "bg-slate-dark-1100",
    // "bg-slate-dark-1200",
    // "bg-slate-dark-alpha-100",
    // "bg-slate-dark-alpha-200",
    // "bg-slate-dark-alpha-300",
    // "bg-slate-dark-alpha-400",
    // "bg-slate-dark-alpha-500",
    // "bg-slate-dark-alpha-600",
    // "bg-slate-dark-alpha-700",
    // "bg-slate-dark-alpha-800",
    // "bg-slate-dark-alpha-900",
    // "bg-slate-dark-alpha-1000",
    // "bg-slate-dark-alpha-1100",
    // "bg-slate-dark-alpha-1200",
    // "bg-slate-light-100",
    // "bg-slate-light-200",
    // "bg-slate-light-300",
    // "bg-slate-light-400",
    // "bg-slate-light-500",
    // "bg-slate-light-600",
    // "bg-slate-light-700",
    // "bg-slate-light-800",
    // "bg-slate-light-900",
    // "bg-slate-light-1000",
    // "bg-slate-light-1100",
    // "bg-slate-light-1200",
    // "bg-slate-light-alpha-100",
    // "bg-slate-light-alpha-200",
    // "bg-slate-light-alpha-300",
    // "bg-slate-light-alpha-400",
    // "bg-slate-light-alpha-500",
    // "bg-slate-light-alpha-600",
    // "bg-slate-light-alpha-700",
    // "bg-slate-light-alpha-800",
    // "bg-slate-light-alpha-900",
    // "bg-slate-light-alpha-1000",
    // "bg-slate-light-alpha-1100",
    // "bg-slate-light-alpha-1200",
    // "variables-bg-brand-primary",
    // "variables-bg-brand-accent"
  ],
};
