version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    image: web:latest
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  docs:
    container_name: docs
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile
    image: docs:latest
    restart: always
    ports:
      - 3001:3000
    networks:
      - app_network

networks:
  app_network:
    external: true